// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using РикконсалтингASP.Models;

namespace РикконсалтингASP.Migrations.DbLemelMigration
{
    [DbContext(typeof(DbLemel))]
    [Migration("20210430100348_AddIDSotrРик")]
    partial class AddIDSotrРик
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("РикконсалтингASP.Models.CompanyLemel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Название")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanysLemel");
                });

            modelBuilder.Entity("РикконсалтингASP.Models.NewUserLemel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyLemelId")
                        .HasColumnType("int");

                    b.Property<int>("IDSotrРик")
                        .HasColumnType("int");

                    b.Property<DateTime>("ДатаИзменения")
                        .HasColumnType("datetime2");

                    b.Property<string>("Имя")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Организация")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Отчество")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Пользователь")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Роль")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ФИОСборное")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Фамилия")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyLemelId");

                    b.ToTable("СотрудникиLemel");
                });

            modelBuilder.Entity("РикконсалтингASP.Models.NewUserLemel", b =>
                {
                    b.HasOne("РикконсалтингASP.Models.CompanyLemel", "CompanyLemel")
                        .WithMany("UsersLemel")
                        .HasForeignKey("CompanyLemelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyLemel");
                });

            modelBuilder.Entity("РикконсалтингASP.Models.CompanyLemel", b =>
                {
                    b.Navigation("UsersLemel");
                });
#pragma warning restore 612, 618
        }
    }
}
